const fs = require('node:fs')
const path = require('node:path')

const desktopRoot = path.resolve(__dirname, '..')
const repoRoot = path.resolve(desktopRoot, '..')

function assert(condition, message) {
  if (!condition) {
    throw new Error(message)
  }
}

function read(relativePath) {
  return fs.readFileSync(path.join(repoRoot, relativePath), 'utf8')
}

const pkg = JSON.parse(fs.readFileSync(path.join(desktopRoot, 'package.json'), 'utf8'))
const resources = pkg.build.extraResources.map((entry) => `${entry.from}->${entry.to}`)

assert(pkg.build.icon === 'build/icon.png', 'Electron Builder deve usar icone proprio do SOG Desktop')
assert(pkg.build.nsis.runAfterFinish === false, 'NSIS nao deve executar atalho do Start Menu ao finalizar')
assert(fs.existsSync(path.join(desktopRoot, 'build', 'icon.png')), 'build/icon.png deve existir')
assert(resources.includes('vendor/agent->agent'), 'extraResources deve incluir vendor/agent -> agent')
assert(resources.includes('vendor/ms-playwright->ms-playwright'), 'extraResources deve incluir vendor/ms-playwright -> ms-playwright')
assert(resources.includes('../docker-compose.desktop.yml->sog-runtime/docker-compose.desktop.yml'), 'extraResources deve incluir docker-compose.desktop.yml')
assert(pkg.scripts['build:win'].includes('prepare:python:win'), 'build:win deve preparar o agente Windows antes do installer')
assert(pkg.scripts['build:win'].includes('generate:icon'), 'build:win deve garantir icone proprio antes do installer')
assert(pkg.scripts['build:win'].includes('npm run verify'), 'build:win deve rodar verificacoes antes do installer')
assert(pkg.scripts['build:win'].includes('verify:packed-runtime'), 'build:win deve validar runtime empacotado')
assert(pkg.scripts['build:win'].includes('verify:win-artifact'), 'build:win deve validar instalador Windows gerado')
assert(pkg.scripts['smoke:win'], 'script smoke:win ausente')
assert(pkg.scripts['smoke:upgrade'], 'script smoke:upgrade ausente')
assert(pkg.scripts['verify:win-artifact'], 'script verify:win-artifact ausente')
assert(pkg.scripts['verify:packed-runtime'], 'script verify:packed-runtime ausente')
assert(pkg.scripts.verify.includes('verify:config'), 'script verify deve testar preservacao de configuracao')
assert(pkg.scripts.verify.includes('verify:redaction'), 'script verify deve testar redacao de diagnostico')
assert(pkg.scripts.verify.includes('verify:plan'), 'script verify deve auditar requisitos do plano')
assert(fs.existsSync(path.join(desktopRoot, 'scripts', 'audit-plan.js')), 'scripts/audit-plan.js deve existir')
assert(fs.existsSync(path.join(desktopRoot, 'scripts', 'verify-packed-runtime.js')), 'scripts/verify-packed-runtime.js deve existir')
assert(pkg.build.files.includes('lib/**/*'), 'Electron Builder deve incluir desktop/lib no app empacotado')

const compose = read('docker-compose.desktop.yml')
assert(!/^\s+agente:/m.test(compose), 'docker-compose.desktop.yml nao deve conter servico agente')
assert(/^\s+api:/m.test(compose), 'docker-compose.desktop.yml deve conter servico api')
assert(/^\s+frontend:/m.test(compose), 'docker-compose.desktop.yml deve conter servico frontend')
assert(/^\s+nginx:/m.test(compose), 'docker-compose.desktop.yml deve conter servico nginx')
assert(compose.includes('SOG_API_IMAGE'), 'docker-compose.desktop.yml deve aceitar imagem API prepublicada')
assert(compose.includes('SOG_FRONTEND_IMAGE'), 'docker-compose.desktop.yml deve aceitar imagem frontend prepublicada')
assert(compose.includes('pull_policy'), 'docker-compose.desktop.yml deve controlar pull de imagens')
assert(compose.includes('SOG_HTTP_PORT'), 'docker-compose.desktop.yml deve permitir porta HTTP configuravel')
assert(compose.includes('type: bind'), 'docker-compose.desktop.yml deve usar volume bind longo para compatibilidade Windows')
assert(!compose.includes('${SOG_DATA_DIR}:/dados'), 'docker-compose.desktop.yml nao deve usar short syntax com path Windows')

const prepare = read('desktop/scripts/prepare-python-runtime.ps1')
assert(prepare.includes('PyInstaller'), 'prepare-python-runtime.ps1 deve gerar executavel com PyInstaller')
assert(prepare.includes('--noconsole'), 'prepare-python-runtime.ps1 deve gerar agente sem janela de console')
assert(prepare.includes('PLAYWRIGHT_BROWSERS_PATH'), 'prepare-python-runtime.ps1 deve fixar PLAYWRIGHT_BROWSERS_PATH')
assert(prepare.includes('--collect-all sog_shared'), 'prepare-python-runtime.ps1 deve incluir dados do pacote sog_shared')
assert(prepare.includes('sog-agent.exe'), 'prepare-python-runtime.ps1 deve validar sog-agent.exe')
assert(prepare.includes('--desktop-smoke'), 'prepare-python-runtime.ps1 deve executar smoke do agente empacotado')

const servico = read('agente/src/servico.py')
const authManager = read('agente/src/modulos/auth_manager.py')
assert(servico.includes('--desktop-smoke'), 'servico.py deve expor smoke desktop do agente')
assert(servico.includes('--desktop-login-smoke'), 'servico.py deve expor smoke visual de login')
assert(servico.includes('sog-agent-smoke'), 'smoke desktop deve validar Chromium Playwright')
assert(authManager.includes('context.storage_state'), 'AuthManager deve salvar storage_state apos login manual')
assert(authManager.includes('Testar Chromium'), 'AuthManager deve orientar teste desktop de Chromium')
assert(authManager.includes('accept_downloads=accept_downloads'), 'AuthManager deve preservar accept_downloads no fallback interativo')

const main = read('desktop/main.js')
assert(fs.existsSync(path.join(desktopRoot, 'lib', 'config-merge.js')), 'lib/config-merge.js deve existir')
assert(fs.existsSync(path.join(desktopRoot, 'lib', 'redact.js')), 'lib/redact.js deve existir')
assert(main.includes('formatEnvValue'), 'main.js deve escrever env com aspas quando valor tiver espaco')
assert(main.includes('parseEnvValue'), 'main.js deve ler env com aspas')
assert(main.includes('findBundledAgent'), 'main.js deve procurar agente empacotado')
assert(main.includes('PLAYWRIGHT_BROWSERS_PATH'), 'main.js deve apontar Chromium empacotado para o agente')
assert(main.includes('testChromiumLogin'), 'main.js deve expor teste visual de Chromium')
assert(main.includes('openDockerDesktop'), 'main.js deve tentar abrir Docker Desktop quando instalado/parado')
assert(main.includes('chooseDataDir'), 'main.js deve abrir seletor grafico de pasta de dados')
assert(main.includes('restartStack'), 'main.js deve permitir reiniciar stack Docker')
assert(main.includes('configurationStatus'), 'main.js deve expor estado de configuracao incompleta')
assert(main.includes('runtimeConfigMissingLabels'), 'main.js deve validar campos obrigatorios dos envs existentes')
assert(main.includes('loadConfig'), 'main.js deve carregar configuracao existente')
assert(main.includes('secretConfigured'), 'main.js deve informar segredos ja configurados sem expor valores')
assert(main.includes('chooseSecret'), 'main.js deve preservar segredos existentes quando campos ficam em branco')
assert(main.includes('SOG_IMAGE_PULL_POLICY'), 'main.js deve preservar politica de pull de imagens Docker')
assert(main.includes('dashboardUrl'), 'main.js deve calcular URL do dashboard com porta configurada')
assert(main.includes('Dashboard aberto no navegador'), 'main.js deve abrir dashboard automaticamente apos subir/reiniciar stack')
assert(main.includes('apiImage'), 'main.js deve carregar imagem Docker API no wizard')
assert(main.includes('frontendImage'), 'main.js deve carregar imagem Docker frontend no wizard')
assert(main.includes("args.push('--build')"), 'main.js deve usar build local apenas quando imagem local for configurada')
assert(main.includes('composeSnapshot'), 'main.js deve incluir Compose no diagnostico')
assert(main.includes('latestAgentLog'), 'main.js deve anexar trecho do log do agente no diagnostico')
assert(main.includes('packageDir'), 'main.js deve gerar pacote/diretorio de diagnostico')
assert(main.includes('agente-ultimas-linhas.log'), 'main.js deve separar log recente no pacote de diagnostico')
assert(main.includes('shell.openPath(packageDir)'), 'main.js deve abrir pasta do pacote de diagnostico')
assert(main.includes('DASHBOARD_SENHA_HASH'), 'main.js deve mascarar segredos do dashboard no diagnostico')

const smoke = read('desktop/scripts/smoke-windows.ps1')
const smokeUpgrade = read('desktop/scripts/smoke-upgrade-preservation.ps1')
const workflowWindows = read('.github/workflows/sog-desktop-windows.yml')
const html = read('desktop/renderer/index.html')
const preload = read('desktop/preload.js')
const renderer = read('desktop/renderer/app.js')
assert(html.includes('name="apiImage"'), 'wizard deve permitir configurar imagem Docker API')
assert(html.includes('name="frontendImage"'), 'wizard deve permitir configurar imagem Docker frontend')
assert(html.includes('name="imagePullPolicy"'), 'wizard deve permitir configurar politica de pull')
assert(html.includes('name="httpPort"'), 'wizard deve permitir configurar porta HTTP')
assert(html.includes('id="choose-data-dir"'), 'wizard deve ter seletor grafico para pasta de dados')
assert(html.includes('id="restart-stack"'), 'UI deve expor botao para reiniciar Docker')
assert(html.includes('id="test-chromium"'), 'UI deve expor botao para testar Chromium visivel')
assert(preload.includes('restartStack'), 'preload deve expor restartStack')
assert(preload.includes('chooseDataDir'), 'preload deve expor chooseDataDir')
assert(preload.includes('testChromiumLogin'), 'preload deve expor testChromiumLogin')
assert(renderer.includes('setInterval'), 'renderer deve atualizar status automaticamente')
assert(smoke.includes('docker compose --env-file $ComposeEnv -f $ComposeFile'), 'smoke Windows deve validar Compose real com .env.compose')
assert(smoke.includes('Read-EnvValue $ComposeEnv "SOG_HTTP_PORT"'), 'smoke Windows deve respeitar porta HTTP configurada')
assert(smoke.includes('Programs\\SOG Desktop\\resources'), 'smoke Windows deve localizar recursos da instalacao NSIS')
assert(smoke.includes('agent\\sog-agent.exe'), 'smoke Windows deve validar agente empacotado instalado')
assert(smoke.includes('throw "Executavel do agente empacotado nao encontrado."'), 'smoke Windows deve falhar se o agente empacotado estiver ausente')
assert(smokeUpgrade.includes('custas.db'), 'smoke upgrade deve verificar custas.db')
assert(smokeUpgrade.includes('pje_storage.json'), 'smoke upgrade deve verificar storage_state PJe')
assert(smokeUpgrade.includes('sistj_storage.json'), 'smoke upgrade deve verificar storage_state SISTJWEB')
assert(smokeUpgrade.includes('upgrade-preservation.pdf'), 'smoke upgrade deve verificar PDFs')
assert(smokeUpgrade.includes('sentinel.png'), 'smoke upgrade deve verificar screenshots')
assert(workflowWindows.includes('npm run smoke:upgrade -- --Mode baseline'), 'workflow Windows deve rodar baseline do smoke de upgrade')
assert(workflowWindows.includes('npm run smoke:upgrade -- --Mode verify'), 'workflow Windows deve rodar verify do smoke de upgrade')
assert(workflowWindows.includes('GITHUB_STEP_SUMMARY'), 'workflow Windows deve publicar resumo de evidencias')

console.log('desktop-package-verification=ok')
