export const ENDPOINTS = {
  LOGIN: '/auth/login',
  ME: '/auth/me',
  LOGOUT: '/auth/logout',
  REFRESH: '/auth/refresh',
  PROCESSOS: '/processos',
  HISTORICO: '/historico',
  HISTORICO_EXPORTAR: '/api/v1/historico/exportar',
  APROVAR: (id: number | string) => `/aprovar/${id}`,
  REJEITAR: (id: number | string) => `/rejeitar/${id}`,
  REPROCESSAR: (id: number | string) => `/processos/${id}/reprocessar`,
  SCREENSHOT: (id: number | string) => `/processos/${id}/screenshot`,
  AGENTE_INICIAR: '/agente/iniciar',
  AGENTE_PARAR: '/agente/parar',
  AGENTE_STATUS: '/agente/status',
  AGENTE_CICLO_ATUAL: '/agente/ciclos/atual',
  AGENTE_ULTIMO_CICLO: '/agente/ciclos/ultimo',
  DASHBOARD_SESSOES: '/dashboard/sessoes',
  PJE_REAUTENTICAR: '/pje/reautenticar',
  SISTJ_REAUTENTICAR: '/sistj/reautenticar',
} as const
